#server:
#  port: 8443
#  ssl:
#    key-store: C:/Program Files/mykeys.jks
#    key-store-password: letmein
#    key-password: Welkom123
#    key-store-type: JKS
#    key-alias: tomcat

#spring.jpa.properties.javax.persistence.schema-generation:
#  create-source: metadata
#  scripts:
#    action: create
#    create-target: create.sql
spring:
  data:
    rest.base-path: /api


logging:
  file:
    path: /var/logs/
    name: TacoCloud.log
  level:
    tacos: DEBUG
    org:
      springframework.security: DEBUG

taco:
  orders:
    pageSize: 10
---
# Production profile properties
spring:
  profiles: prod

  logging:
    level:
      tacos: WARN

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacodb
    password: tacopassword
#    schema:
#      - order-DELEGATED_TO_SPRING_DATA_schema.sql
#      - ingredient-DELEGATED_TO_SPRING_DATA_schema.sql
#      - taco-DELEGATED_TO_SPRING_DATA_schema.sql
#      - user-DELEGATED_TO_SPRING_DATA_schema.sql
#    data:
#      - ingredient-data.sql

#spring:
#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacodb
#    password: tacopassword
#    schema:
#      - order-DELEGATED_TO_SPRING_DATA_schema.sql
#      - ingredient-DELEGATED_TO_SPRING_DATA_schema.sql
#      - taco-DELEGATED_TO_SPRING_DATA_schema.sql
#      - user-DELEGATED_TO_SPRING_DATA_schema.sql
#    data:
#      - ingredient-data.sql

#spring:
#  datasource:
#    jndi-name: java:/comp/env/jdbc/tacoCloudDS
#    TODO: JNDI checken